[epc]
chg_dic = {"La":5.5,"Ni":9.0,"O":3.0}
ucellidx = [5,5,5]
dQ = 0.02
inDir = 555
poscar_ucell = POSCAR_u
infile_in_s = input_s.dat
infile_split_s = 23
infile_out = input.dat
subfile_s = sub_openmx_s
bandDir = epc_band
phononDir = phonon
valname = band_val_k.npy
vecname = band_vec_k.npy
phvalname = val.npy
phvecname = vec.dat
dhamilDir = dhamil
epcDir = epc_all
IsH5 = False
H5HamName = out/hamiltonians
H5OlpName = output/overlaps
H5OlpNum = 1
H5DrName = output/overlaps
H5DrNum = 1
nq = [50,50,50]
atom = [1,1,2]
orbital = [26,14,13]
Kpoint = [[0,0,0],[0,1/2,0],[1/2,1/2,0],[0,0,0],[0,0,1/2],[0,1/2,1/2],[1/2,1/2,1/2],[0,0,1/2]]
IsAllVec = False
bmin = 19
bmax = 22
IsAllKlist = True
emin = -20.0
emax = 20.0
EpcType = K
# type: A K Q
phonon_method = F
dhamil_method = F
# method: F B C

[ucell]
IsH5_u = False
infile_in_u = input_u.dat
infile_split_u = 23
subfile_u = sub_openmx_u

[sub]
SUB_NUM_HAMIL = 2
TIME_MAX_HAMIL = 3600
# second

[mpi]
DHAMIL_BLOCK = 4
NMODES_BLOCK = 12
# scalapack parameter
M_BLOCK = 64
N_BLOCK = 64
