[epc]
chg_dic = {"Mo":7.0,"S":3.0,"C":2.0}
ucellidx = [7,7,1]
dQ = 0.01
inDir = 77
poscar_ucell = POSCAR_u
infile_in_s = input_s.dat
infile_split_s = 21
infile_out = input.dat
subfile_s = sub_openmx_s
bandDir = epc_band
phononDir = phonon
valname = band_val_k-30.npy
vecname = band_vec_k-30.npy
phvalname = val-30.npy
phvecname = vec-30.dat
dhamilDir = dhamil
epcDir = epc_all
IsH5 = False
H5HamName = out/hamiltonians
H5OlpName = output/overlaps
H5OlpNum = 1
H5DrName = output/overlaps
H5DrNum = 1
nq = [30,30,1]
atom = [2]
orbital = [13]
Kpoint = [1/3,1/3,0]
IsAllVec = False
bmin = 3
bmax = 4
IsAllKlist = False
emin = -4.0
emax = 3.0
EpcType = A
# type: A K Q
phonon_method = F
dhamil_method = F 
# method: F B C

[ucell]
IsH5_u = False
infile_in_u = input_u.dat
infile_split_u = 21
subfile_u = sub_openmx_u

[sub]
SUB_NUM_HAMIL = 2
TIME_MAX_HAMIL = 360
# second

[mpi]
DHAMIL_BLOCK = 4
NMODES_BLOCK = 6
# scalapack parameter
M_BLOCK = 128
N_BLOCK = 128
