[epc]
# input files
Ispin = 2
para_dic = {"Ni":"10.0 8.0 0.0 0.0 0.0 0.0 0  off"}
#para_dic = {"Ni":"10.0 8.0  off"}
ucellidx = [7,7,7]
dQ = 0.01
inDir = 7_so
poscar_ucell = POSCAR_u
infile_in_s = input_s.dat
infile_split_s = 21
infile_out = input.dat
subfile_s = sub_openmx_s

# band files
bandDir = epc_band
valname = band_val_k-10.npy
vecname = band_vec_k-10.npy
basselname = bassel-10.npy
spinname = spinDM-10.npy

# phonon files
phononDir = phonon
ifcname = fc_avg.npy
ifcRcut = 5.0
phvalname = val-10.npy
phvecname = vec-10.dat
phonon_method = F
# method: F B C

# epc calculation
dhamilDir = dhamil
epcDir = epc_all
epcname = epc_all_p-10.dat
IsH5 = True
H5HamName = out/hamiltonians
H5OlpName = out/overlaps
H5OlpNum = 1
H5DrName = output/overlaps_d
H5DrNum = 16
nq = [10,10,10]
atom = [1]
orbital = [14]
Kpoint = [[0,0,0],[0,1/2,0],[1/3,1/3,0],[0,0,0]]
IsAllVec = False
bmin = 17
bmax = 19
IsAllKlist = False
emin = -6.21231611
emax = -5.21231611
EpcType = A
# type: A K Q
dhamil_method = F
# method: F B C

[ucell]
IsH5_u = True
H5HamName_u = out/hamiltonians
H5OlpName_u = output/overlaps
H5OlpNum_u = 4
infile_in_u = input_u.dat
infile_split_u = 21
subfile_u = sub_openmx_u

[sub]
SUB_NUM_HAMIL = 2
TIME_MAX_HAMIL = 360
# second

[mpi]
DHAMIL_BLOCK = 4
NMODES_BLOCK = 3
# scalapack parameter
M_BLOCK = 32
N_BLOCK = 32
