[epc]
# input files
Ispin = 2
para_dic = {"La":"5.5 5.5 off","Ni":"9.0 9.0 off","O":"3.0 3.0 off"}
ucellidx = [5,5,5]
dQ = 0.02
inDir = 555
poscar_ucell = POSCAR_u
infile_in_s = input_s.dat
infile_split_s = 23
infile_out = input.dat
subfile_s = sub_openmx_s

# band file
bandDir = epc_band
valname = band_val_k-50.npy
vecname = band_vec_k-50.npy
basselname = bassel-50.npy
spinname = 

# phonon files
phononDir = phonon
ifcname = fc_avg.npy
ifcRcut = 
phvalname = val-50.npy
phvecname = vec-50.dat
phonon_method = F
# method: F B C

# epc calculation
dhamilDir = dhamil
epcDir = epc_all
epcname = epc_k-50.dat
IsH5 = False
H5HamName = out/hamiltonians
H5OlpName = output/overlaps
H5OlpNum = 1
H5DrName = output/overlaps
H5DrNum = 1
nq = [50,50,50]
atom = [1,1,2]
orbital = [26,14,13]
Kpoint = [[0,0,0],[0,1/2,0],[1/2,1/2,0],[0,0,0],[0,0,1/2],[0,1/2,1/2],[1/2,1/2,1/2],[0,0,1/2]]
IsAllVec = False
bmin = 19
bmax = 22
IsAllKlist = True
emin = -20.0
emax = 20.0
EpcType = K
# type: A K Q
dhamil_method = F
# method: F B C

[ucell]
IsH5_u = False
infile_in_u = input_u.dat
infile_split_u = 23
subfile_u = sub_openmx_u

[sub]
SUB_NUM_HAMIL = 2
TIME_MAX_HAMIL = 3600
# second

[mpi]
DHAMIL_BLOCK = 4
NMODES_BLOCK = 12
# scalapack parameter
M_BLOCK = 64
N_BLOCK = 64
